export const ADD_TASK = 'ADD_TASK';
export const COMPLETE_TASK_HANDLER = 'COMPLETE_TASK_HANDLER';
export const DELETE_TASK = 'DELETE_TASK';


export const DELETE_FOLDER = 'DELETE_FOLDER';
export const ADD_FOLDER = 'ADD_FOLDER';
export const SELECT_FOLDER = 'SELECT_FOLDER';

